version: '3.1'
services:
  server:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.2.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env

  # composer:
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: composer.dockerfile
  #   volumes:
  #     - ./src:/var/www/html

# docker compose run --rm composer create-project --prefer-dist laravel/laravel .